travis:
  secure:
    BINSTAR_TOKEN: ZWwzCCvxkfVJG9m8LCbrEEZW7MdJiPpjwo5+NkH2hkInA7nGuq4Lu+u0nV6v/TRK6OYAq8tWDCGzngg3HbdqoRQKGC6pV1P9/Zc/TYj65N9Ut8eZXbkEivkYddC84mcfGN9iflhk+V/qHJ48PF6lmomDP1yUtTqqJwo7vvzPCJJ0rQbht4YymXZsp6mhvi+Twq7mf8ax/gcT4rBYHbwvWbYNH46Ab8ZyXpQdUI2gAONVyH0efk12DU9+yLqNTg8/bLuowYl0krwvJaLaIG4hCUneeh0+03G5hH5c0OsJp3Pwb8cOPM2qMafOrhKZV+6AV2QiDuLz4wIPyNRaPMcbOhbnffeukUQNkM+vumtbGoskVmTuUMah5+VFKOif4Cbu4Z+Ls88+AKoW/cJsJl7ollaW/rhl3bPKWBpIeDfxHA+RuEfJijNjeUnCuIO3MM73Ykp/PIasFK+GN0+EvdcCy2ATSXU6KrZxuDFWNEh7GNjBIq2W/vSPsPc4eSs4NyaZsODQYrWZwB2ZRqRNlLZyqzEut4SkvknckwA9Qb5dBl8DjwmKAsGigJcRT6hjdWVwMyWkPErTO9FjaHXw2hvN2TvexVLAg5Ianqy81gxrxMTbftE/QjhixpjUt01h8ilwqIMc4w9DIM71cdZyhwPM7sSV98Xky+vaquz1gkFOu2E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
